### ISSUE TITLE
Opera 111.0.5168.43 has been released

### ISSUE THREAD

**Issue by burnout426** [flathub/com.opera.Opera#110]
Just a friendly reminder that Opera 111.0.5168.43 has been released and the Opera Flatpak needs to be updated. Thanks.

**Comment by WendelBitencourt** [comment]
Do you need help? I don't have much technical knowledge, but I would like to assist if you are very busy.

**Comment by Gaeldrin** [comment]
Hello and thank you, I noticed the failing builds too this time. :)
Feels like I am almost repeating myself but Flatpak decided to change its behaviour [[1](https://docs.flathub.org/blog/linter-restricting-automatic-merge/)] so I need to change the app correspondingly. It is already in process but the lack of documentation (and my lack of understanding of its organization) makes it slow and painful. My plan is to change both opera itself and the codecs to extra-data, which should enable automatic updates again.

**Comment by burnout426** [comment]
Thanks for your time.
