### ISSUE TITLE
Chromium proprietary codecs aren't working

### ISSUE THREAD

**Issue by mwoz123** [flathub/com.opera.Opera#28]
After recent update ( to ver 99.0.4788.47) it keeps on dispalying "Page crashed (..) Reload this page" on various pages.

e.g. on:
https://www.youtube.com
https://www.youtube.com/watch?v=RsELrcVNzG0

@Gaeldrin, @barthalion - could you help ? 
This happens on my 2 PCs with Ubuntu 22.04.

**Comment by Gaeldrin** [comment]
Confirmed, I have the same behaviour. For now I made a rollback to version `99.0.4788.31` so the users are not impacted, seems to work fine.

As for the issue, I don't see anything related in the [Opera changelog](https://blogs.opera.com/desktop/changelog-for-99/). When executed from command line, I get this:
```
~/git/com.opera.Opera$ flatpak run --devel com.opera.Opera --private
  ...startup messages...
[0605/124031.306768:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
```

For me, that is it. At least for now, I have no idea how to proceed, quick search did not help and I must go. Do you have any idea @barthalion ? Any help is appreciated.

**Comment by mwoz123** [comment]
Thanks but is there a chance that users (like me), who'd already installed this crashing version, will get upgrade/rollback to working one? 

I'm unfamiliar with flatpak but maybe you could you add, to version id, a suffix (e.g. `-1`, `-hotfix / -rollback` whatever) to be caught by the flatpak upgrade system and to force not-crashing Opera version installation ?

**Comment by Gaeldrin** [comment]
@mwoz123 That should be the case, everyone should get working version. There is 3 hour waiting time that I cannot do anything about. I am not too familiar with flatpak myself so I could be wrong about that - if you can confirm successful downgrade automatically after few more hours, please let me know.

What is certain, you can downgrade at any time manually if you cannot wait:
https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading

**Comment by barthalion** [comment]
It probably only worked by a coincidence. Arch packages ffmpeg codecs for Opera separately, most likely to avoid these version mismatches: https://gitlab.archlinux.org/archlinux/packaging/packages/opera-ffmpeg-codecs/-/blob/main/PKGBUILD

**Comment by Gaeldrin** [comment]
> Guys are you sure it's codecs issue? we you able to find a working (youtube) verson ?
> 
> .. But now I'm not able to find a working version :(

Yes, I am sure, I verified it and you can too. The steps are to
 1. install Opera flatpak before I removed the Chromium codecs and then
 2. downgrade the codecs to compatible version as follows:

```shell
# downgrade Opera to 99.x.x.47 with codecs: 
 sudo flatpak update --commit=e3abd33637dc3dd51257118a03cc5df5234e2b2b7f9e4a6485563b404afb71c5 com.opera.Opera
# downgrade codecs to Chromium 113 (base of Opera 99): 
 sudo flatpak update --commit=41da9adab9385bfc3bfa80b95f23ac6ace85b46032b120aeeb87676fbd894cf7 org.chromium.Chromium.Codecs
```

As for how to fix this, I would like to ask @barthalion or anyone with knowledge about Flatpak for recommendation. I imagine there is a way to make the dependency install specific commit but that would mean manual change every time the Chromium base changes with all the drawbacks..

**Comment by Gaeldrin** [comment]
Thank you, I've read it but unfortunately I don't know how to do that.

I've come up with an automated way of getting the correct library (using ArchLinux package of all things :) ) but Flatpak build commands are not the correct place for my construct and I don't know of another way. And as I already spent some time working on a platform I am not familiar with and I don't want to spend an unknown amount of time more to learn it properly, I will just leave here a template in shell showing how the problem could be fixed. Maybe someone will complete it (I feel it is a fine 1st issue) or maybe I will come back to it in the future. But it will probably not happen too soon.

```shell
# 1. get latest Chromium version
codecversion=$(wget https://gitlab.archlinux.org/archlinux/packaging/packages/opera-ffmpeg-codecs/-/raw/main/PKGBUILD -q -O - | grep "pkgver=" | cut -f2 -d"=")
# 2. get matching libffmpeg.so
wget https://ftp5.gwdg.de/pub/linux/archlinux/extra/os/x86_64/opera-ffmpeg-codecs-$(codecversion)-1-x86_64.pkg.tar.zst | tar --zstd -xf
# 3. move the library to opera/lib_extra/ or link it
# 4. clean the downloaded files if necessary
```

**Comment by mwoz123** [comment]
I also can't help here :(
@barthalion could you help?

**Comment by dinhokusanagi** [comment]
https://github.com/flathub/com.google.Chrome

These people should know how to solve

**Comment by mwoz123** [comment]
I was trying to workaround the issue.
Found [arch archive repo](https://archive.archlinux.org/packages/o/opera-ffmpeg-codecs/) contains a lot of opera-ffmpeg. 

Unfortunately copying  (not exact the same but simliar version) `libffmpeg.so` to `/var/lib/flatpak/app/com.opera.Opera/current/active/files/opera/lib_extra` but still non-youtube videos didn't worked :(

So based on [arch PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/opera-ffmpeg-codecs/-/blob/main/PKGBUILD?ref_type=heads) file and Opera.yaml I tried to create Opera.ffmpeg flatpak build yaml:
https://github.com/mwoz123/opera-ffmpeg-flatpak/blob/master/com.opera.Opera.ffmpeg.yaml

but as I never did C++ nor Flatpak coding I got stuck at: 
```bash
$ flatpak-builder build com.opera.Opera.ffmpeg.yaml -v --force-clean
(...)
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-18-init-9505-g10664813-1.tar.xz 
<urlopen error [Errno -3] Temporary failure in name resolution>
Failed to download prebuilt clang package clang-llvmorg-18-init-9505-g10664813-1.tar.xz
Use build.py if you want to build locally.
Exiting.
```

**Comment by Gaeldrin** [comment]
> I was trying to workaround the issue. Found [arch archive repo](https://archive.archlinux.org/packages/o/opera-ffmpeg-codecs/) contains a lot of opera-ffmpeg.
> 
> Unfortunately copying (not exact the same but simliar version) `libffmpeg.so` to `/var/lib/flatpak/app/com.opera.Opera/current/active/files/opera/lib_extra` but still non-youtube videos didn't worked :(

Hello again. :)

It's weird that it doesn't work for you, just tested this and it works for me (using current Opera version: 106.0.4998.19). Got the [version 120](https://archive.archlinux.org/packages/o/opera-ffmpeg-codecs/opera-ffmpeg-codecs-120.0.6099.109-1-x86_64.pkg.tar.zst), unpacked and moved to `/var/lib/flatpak/app/com.opera.Opera/current/active/files/opera/lib_extra/libffmpeg.so` and now I have support for h.264 codec.

**Comment by mwoz123** [comment]
Right I does work this way:) I'm on the same Opera version right now. 

But not sure if it will work always? if we can simply use arch bundled codecs as it doesn't exactly match the chromium version we have? As I'm already upgraded I cannot confirm it was my mistake or just the mismatch of the minor version chromium-ffmpeg and the opera-chromium...

----
I'd overlooked your comment, and I meantime I pushed forward work for https://github.com/mwoz123/opera-ffmpeg-flatpak/

As I never did flatpak build - right now the issue is `flatpak-builder` throws `gn: command not found`.
I'm using `buildsystem: simple`, as it's used by [Chromium](https://github.com/flathub/org.chromium.Chromium/blob/75c9aa3c1cf43e8094156bc50be93ec419b7578d/org.chromium.Chromium.yaml#L106) and `buildsystem: cmake-ninja` throws `Error: module: opera-ffmpeg: Can't find CMakeLists.txt` 

I'll probably leave the work in case we'd want to go back to it, as it should be more solid solution...

**Comment by ShoutHouse** [comment]
I am currently experiencing this issue, without the crash window. It is presenting itself as 

Nobara 39 (Fedora) 
Kernel 6.7
KDE Plasma 5.27.10
kwin
wayland
Opera One: 107.0.5045.15



The fix listed above works. Placing the codec from my flatpak install of Vivaldi into the ~/lib_extra folder does fix the issue. 

Previously, I was only able to play video at YouTube and nowhere else including Amazon, Twitch, and more. Everywhere was saying that there was no supported file to access.


Is the wrong ffmpeg.so file being provided? Currently the flatpak seems not to include the ~/lib_extra folder at all. Am I missing something or is that a possible oversight? Is it possible to have an option to set the main location that our OS places the ffmpeg.so file so that it can be maintained with the system update cycle?

**Comment by nmondal** [comment]
Crashing out. I  replaced the `libffmpeg.so` with something else, it used to work, now it is crashing out pages.

```
Zorin 16.3
Opera One(version: 107.0.5045.15)
Chromium version:121.0.6167.140
```
No matching ffmpeg for the same version anywhere yet.

**Comment by mwoz123** [comment]
Guys how about using Vivalidi's ffmpeg codecs:
https://repo.herecura.eu/herecura/x86_64/
and archive versions:
https://archive.archlinux.org/packages/v/vivaldi-ffmpeg-codecs/
?

Tested on my:
```
Opera One(version: 107.0.5045.21)
Opera is up to date
Update stream:Stable
System:Freedesktop SDK 23.08 (Flatpak runtime) (x86_64; Unity)
Chromium version:121.0.6167.160
```
using `vivaldi-snapshot-ffmpeg-codecs-122.0.6261.21-1-x86_64.pkg.tar.zst` 
extacted `libffmpeg.so.6.6` & copied as `/var/lib/flatpak/app/com.opera.Opera/current/active/files/opera/lib_extra/libffmpeg.so`

Seems to work: 
https://help.vivaldi.com/desktop/media/html5-proprietary-media-on-linux/
:)

**Comment by ZariTen** [comment]
@mwoz123 solution seems to work, so I created a script that automates that. If anyone wants it: https://gist.github.com/ZariTen/d16336785d4ee50e875c3b261d5cf488 . (Always remember to analyse shell scripts before executing them, they can be dangerous!)

**Comment by mwoz123** [comment]
It's from help/about from Opera url: 
`opera://about/` in address bar

**Comment by mwoz123** [comment]
It might be hard to automate picking it from there. 
But how about incorporating (modified) [ZariTen's script](https://github.com/flathub/com.opera.Opera/issues/28#issuecomment-2041182099) to get latest codecs?

**Comment by Gaeldrin** [comment]
Let's see where [this](https://github.com/flathub/flathub/pull/5174) goes :)
