### ISSUE TITLE
Browser language is not present in settings 

### ISSUE THREAD

**Issue by n1c0saurio** [flathub/com.opera.Opera#44]
As title says, on a fresh install Opera didn't default to system language, nor the options to change it on setting is present.

The only language related options are these:
![imagen](https://github.com/flathub/com.opera.Opera/assets/16579247/76f72f1a-ef51-471a-97d0-5e462b9fed59)

While this is absent:
![imagen](https://github.com/flathub/com.opera.Opera/assets/16579247/67f71fed-46f9-4ce7-bbfe-6c28cd241f8b)

**Comment by Gaeldrin** [comment]
I honestly cannot change the language in present versions of Opera even when I install it directly from their webpage and not just through Flatpak (tested on Linux Mint/Ubuntu). I am not sure what version is the second screenshot from, but as far as I can tell, Opera is only available in English on current versions on Linux. :/

**Comment by Shogu** [comment]
Hello.

You can change the language by edsiting the shortcut of Opera : for example, in french, the new syntax is this one : /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=opera --file-forwarding com.opera.Opera @@u **--lang=fr** %U @@

I added --lang=fr

After a restart, the Opera icon should disappear temporarly, and the Gnome session shut down, but everything goes fine after! A bit trivial but it works!
