### ISSUE TITLE
Wayland permission

### ISSUE THREAD

**Issue by chrisawi** [flathub/com.opera.Opera#63]
Opera apparently can be configured to use Wayland, so it should have `--socket=wayland` in its manifest in addition to x11.

**Comment by Gaeldrin** [comment]
Do you have any specific information that you could share here? I cannot verify that myself but about a year ago I received info from Flatpak devs that it does not work on Wayland.

https://github.com/flathub/flathub/pull/3772#discussion_r1061264498

**Comment by chrisawi** [comment]
The problem with the original manifest was the use of `socket=fallback-x11`. That indicates that the app uses Wayland natively by default, and thus blocks access to the X11 socket in a Wayland session for security.

Opera doesn't use Wayland by default, but like other Chromium-based apps, you can set a flag (opera://flags/#ozone-platform-hint) to make it do so. For that to work, the `socket=wayland` permission needs to be enabled.

For reference, [Chromium's manifest](https://github.com/flathub/org.chromium.Chromium/blob/master/org.chromium.Chromium.yaml#L19-L20) has:
```
  - --socket=x11
  - --socket=wayland
```

This allows users to enable Wayland for themselves and has no effect on the default behavior.

**Comment by Gaeldrin** [comment]
Thank you very much, it will be available in a few hours.
